client_config_backend: settings
client_config:
  client_id: 260797393801-e233c8344o59l03dghsg096mnbeqd2p8.apps.googleusercontent.com
  client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True
oauth_scope:
  - https://www.googleapis.com/auth/drive
